### ISSUE TITLE
You need to get the INBOX section of mygov website fixed!

### ISSUE THREAD

**Issue by mlockrey** [govau/inbox-alpha#5]
The inbox section of the [MYGOV](https://my.gov.au/) website has absolutely hopeless navigation! A few basic issues for you to address via leveraging the DTA's "clout" over all departments include:

- "back" navigation choice always takes you back to page 1 of your **INBOX!** Even if you're looking at letters from a Government agency whilst you're on pages 5 and 6+ etc etc! #hopeless UIX

- there's no way for a user to mark all letters in **INBOX** as "read" (rather you have to go to each individual letter in **INBOX** and then use the "back" navigation option to make the "READ" and remove the bolding styles applied etc). Quickly gets very tedious when you have to open unread letters on pages 3, 4 and 5+ when you get 30-plus letters from Child Support in 24 hours!

- on the MacBook Pro, my letter attachments don't even open half the time! But there's probably not much you can do about that one...

**Comment by jonathaningram** [comment]
Hi @mlockrey, thank you for getting in touch. The DTA is always continually working on improving the user experience. 
Your feedback is valuable and we invite you to share your feedback with myGov official communication channels using the following link: https://www.humanservices.gov.au/individuals/contact-us/mygov-complaints-and-feedback
